name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output packages /p:Version=1.0.0
      if: github.ref == 'release'
    - name: Push
      run: dotnet nuget push packages/ --api-key ${{ secrets.NUGET_KEY }}
      if: github.ref == 'release'
