name: CI

on: 
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.0
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output packages
    - name: Push
      run: dotnet nuget push packages/ --api-key ${{ secrets.NUGET_KEY }}
